<a href="https://colab.research.google.com/github/pankajmahato907/AI_Workshops/blob/main/AI_ML_Worksheet_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Python

In [1]:
# python version
import sys

if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World")
    print(f"Python version: {sys.version_info.major}")
else:
    print("Please use python 3.6 or more.")

Hello, World
Python version: 3


In [1]:
# python datatypes -> List
my_list = [1,2,3]
print("Original List: ", my_list)

# modyfying the list (changing contents)
my_list.append(4)
print("Modified List: ", my_list)

Original List:  [1, 2, 3]
Modified List:  [1, 2, 3, 4]


In [2]:
# python datatype -> Tuple
my_tuple = (1,2,3)
print("Original tuple: ", my_tuple)

# modifing the tuple generate error as it is immutable

Original tuple:  (1, 2, 3)


In [3]:
# Numeric datatypes
age = 23
marks = 90.5

print("Data type of age is ", type(age))
print("Data type of marks is ", type(marks))

Data type of age is  <class 'int'>
Data type of marks is  <class 'float'>


In [4]:
# sequence
name = "Pankaj Kumar Mahato"
greeting = "Namaste"
address = "Kotehwor"

print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))

# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])

# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: P
The last letter of the name is: o
The second letter to the fourth of the name is: ank
The first two letters of the name are: Pa
Substring starting from the third letter is: nkaj Kumar Mahato


In [5]:
# List
list1 = [1,2,3]
mixed_list = [1,"Apple",4.5]

# List is mutable
mixed_list[1] = "Orange"
print(mixed_list)

[1, 'Orange', 4.5]


In [6]:
#  Tuple Mutability
my_tuple = (1,2,3,"Apple")
my_tuple[1] = "Ten"

TypeError: 'tuple' object does not support item assignment

In [7]:
colors = ("red", "green", "yellow", "blue")
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
colors[0] = "purple"

print(colors)

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


TypeError: 'tuple' object does not support item assignment

In [8]:
# Dictionary
person = {
    name: "Pankaj Kumar Mahato",
    age: 23,
    address: "Koteshwor"
}

print(f"""
    Hello, World. I am {person[name]}, {person[age]} of age, from {person[address]}
""")


    Hello, World. I am Pankaj Kumar Mahato, 23 of age, from Koteshwor



In [9]:
# Set

unique_numbers = {1,2,33,33,45,4,2,1}
print(unique_numbers)

{1, 2, 33, 4, 45}


In [10]:
# Boolean

is_student = True
has_license = False

print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [11]:
# Conditional

is_ram_a_god_name = True

if is_ram_a_god_name:
    print("Worship him.")
else:
    pass

Worship him.


In [12]:
# Loops

n = 15
while n>10:
    n -= 1

for i in range(1, n):
    if i%2 == 0:
        print("I am even, ", i)

I am even,  2
I am even,  4
I am even,  6
I am even,  8


In [13]:
# Function with doc strings

def is_even(n):
"""
Return if the number is even or odd

Parameters:
    n (int)

Returns:
    boolean value
"""
if n%2 == 0:
            return True

n = int(input("Enter a number "))

if is_even(n):
    print(f"{n} is even")
else:
    print(f"{n} is odd")

IndentationError: expected an indented block after function definition on line 3 (<ipython-input-13-372cbf66ab8a>, line 4)

In [14]:
def temperature_converter():
    """
Converts temperature between Celsius and Fahrenheit.
This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
Fahrenheit to Celsius)
and then asks for the temperature value. It calculates and returns the converted temperature.
Returns:
    float: The converted temperature value.
"""
    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")
    if choice == "1":
    # Celsius to Fahrenheit conversion
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}C is equal to {fahrenheit}F")
        return fahrenheit
    elif choice == "2":
        # Fahrenheit to Celsius conversion
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}F is equal to {celsius}C")
        return celsius
    else:
        print("Invalid choice. Please enter 1 or 2.")
        return None
# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 2
Enter temperature in Fahrenheit: 30
30.0F is equal to -1.1111111111111112C


-1.1111111111111112

In [15]:
# Error handling
def check_age(age):
    if age < 0:
        raise ValueError("Age cannot be negative.")
    else:
        print("Valid age")

try:
    check_age(-1)
except ValueError as e:
    print(e)

Age cannot be negative.


# **TODO Tasks**

## Task-1

In [16]:
# Length
def convert_length(n):
    """
        Convert the length based on the unit
        Parameters:
            Value to convert
        Returns:
            Converted value
    """
    try:
        option = int(input("Do you want to convert it to meter(1) or feet(2) "))

        if option == 1:
            return n/3.28084
        elif option == 2:
            return n * 3.28084
    except ValueError:
        print("Inappropriate option or value")
    except TypeError:
        print("Cannot perform due to the type issue")

print(f"{convert_length('abc')}")

Do you want to convert it to meter(1) or feet(2) 1
Cannot perform due to the type issue
None


In [17]:
# Weight
def convert_weight(n):
    """
        Convert the weight based on the unit
        Parameters:
            Value to convert
        Returns:
            Converted value
    """
    try:
        option = int(input("Do you want to convert it to pound(1) or kg(2) "))

        if option == 1:
            return n*2.20462
        elif option == 2:
            return n /2.20462
    except ValueError:
        print("Inappropriate option or value")
    except TypeError:
        print("Cannot perform due to the type issue")

print(f"{convert_weight(10)}")

Do you want to convert it to pound(1) or kg(2) 1
22.0462


In [18]:
# Volumn
def convert_volumn(n):
    """
        Convert the volumn based on the unit
        Parameters:
            Value to convert
        Returns:
            Converted value
    """
    try:
        option = int(input("Do you want to convert it to gallon(1) or liter(2) "))

        if option == 1:
            return n/0.219969
        elif option == 2:
            return n * 0.219969
    except ValueError:
        print("Inappropriate option or value")
    except TypeError:
        print("Cannot perform due to the type issue")

print(f"{convert_volumn(10)}")

Do you want to convert it to gallon(1) or liter(2) 2
2.19969


## Task-2

In [ ]:
from re import split
# Create a Python program that performs various mathematical operations on a list of numbers.

def math_operation():
    try:
        option = int(input("What operation do you want to do today?\n1.Find Max\n2.Find Min\n3.Find Sum\n4.Find Average\n"))
        if option>4 or option<1:
            raise ValueError("Invalid Option")

        numbers = input("Enter the numbers seperated by space: ")
        arr = numbers.split(" ")
        arr = [int(i) for i in arr]

        if(option == 1):
            print(f"The max in the array is: {max(arr)}")
        elif(option == 2):
            print(f"The min in the array is: {min(arr)}")
        elif(option == 3):
            print(f"The sum of numbers in the array is: {add(arr)}")
        elif(option == 4):
            print(f"The average of numbers in the array is: {average(arr)}")

    except ValueError:
        print("Invalid Option Selected")
    except TypeError:
        print("Please input numbers only")

def max(n):
    """
        Returns the maximum number in the list

        parameters:
            n (array of numbers)

        returns:
            max_number
    """
    max_num = n[0]
    for i in range(1,len(n)):
        if max_num < n[i]:
            max_num = n[i]

    return max_num

def min(n):
    """
        Returns the minimum number in the list

        parameters:
            n (array of numbers)

        returns:
            min_number
    """
    min_num = n[0]
    for i in range(1,len(n)):
        if min_num > n[i]:
            max_num = n[i]

    return min_num

def add(n):
    """
        Returns the sum of numbers in the list

        parameters:
            n (array of numbers)

        returns:
            max_number
    """
    sum = 0
    for i in range(len(n)):
        sum += n[i]

    return sum

def average(n):
    """
        Returns the average of numbers in the list

        parameters:
            n (array of numbers)

        returns:
            average
    """
    sum = 0
    for i in range(len(n)):
        sum += n[i]

    return sum/len(n)

# begin the program
math_operation()


## Exercise on List Manipulation:

In [ ]:
# Exercise on List Manipulation
# Write a Python function that extracts every other element from a list, starting from the first element.

def extract_every_other(lst):
    """
        Extracts every other element from a list

        returns:
            new_list (array)
    """
    new_array = []
    for i in range(len(lst)):
        if i%2 != 0: continue
        new_array.append(lst[i])

    return new_array

res = extract_every_other([1,2,3,4,5,6])
print(res)


[1, 3, 5]


In [ ]:
# Write a Python function that returns a sublist from a given list, starting from a specified index and
# ending at another specified index.

def get_sublist(lst, start, end):
    return lst[start:end]

res = get_sublist([1,2,3,4,5,6,7], 1,2)
print(res)

[2]


In [ ]:
# Reverse a List Using Slicing

def reverse_list(lst):
    return lst[::-1]

res = reverse_list([1,2,3,4,5])
print(res)

[5, 4, 3, 2, 1]


In [ ]:
# 4. Remove the First and Last Elements

def remove_first_last(lst):
    return lst[1:len(lst)-1]

res = remove_first_last([1,2,3,4,5])
print(res)

[2, 3, 4]


In [ ]:
# 5. Get the First n Elements

def get_first_n(lst, n):
    return lst[:n]

res = get_first_n([1,2,3,4,5], 3)
print(res)

[1, 2, 3]


In [ ]:
# 6. Extract Elements from the End
def get_last_n(lst, n):
    return lst[n:]

res = get_last_n([1,2,3,4,5], 3)
print(res)

[4, 5]


In [ ]:
# Extract Elements in Reverse Order

def reverse_skip(lst):
    return lst[::2][::-1]

res = reverse_skip([1,2,3,4,5,6])
print(res)

[5, 3, 1]


## Exercise on Nested List:

In [ ]:
# 1. Flatten a Nested List

def flatten(lst):
    # List comprehension answer ->
    # return [item for sublist in lst for item in sublist]
    res = []
    for i in lst:
        for j in i:
            res.append(j)

    return res

res = flatten([[1, 2], [3, 4], [5]])
print(res)

[1, 2, 3, 4, 5]


In [ ]:
# 2. Accessing Nested List Elements

def access_nested_element(lst, indices):
    return lst[indices[0]][indices[1]]

res = access_nested_element([[1, 2], [3, 4], [5]], [1,1])
print(res)

4


In [ ]:
# 3. Sum of All Elements in a Nested List:

def sum_nested(lst):
    # List comprehension answer ->
    # return [item for sublist in lst for item in sublist]
    res = []
    for i in lst:
        for j in i:
            res.append(j)

    return sum(res)

res = sum_nested([[1, 2], [3, 4], [5]])
print(res)

15


In [ ]:
# 4. Remove Specific Element from a Nested List

def remove_element(lst, elem):
    for i in lst:
        if elem in i:
            i.remove(elem)

    return lst

res = remove_element([[1, 2], [3, 4], [2,5]], 2)
print(res)

[[1], [3, 4], [5]]


In [ ]:
# recusrion practice
def factorial(n):
    if n == 1:
        return 1
    else:
        return n * factorial(n-1)

factorial(5)

120

In [ ]:
# 5. Find the Maximum Element in a Nested List:
# Write a Python function that finds the maximum element in a nested list (regardless of depth).

def flatten_list(lst):
    # convert it to string, strip unnecessary characters
    tmp = str(lst)
    tmp = tmp.strip("[]")
    tmp = tmp.replace("[", "").replace("]", "").replace(" ", "")
    t_arr = tmp.split(",")

    return [int(i) for i in t_arr]


def find_max(lst):
    return max(flatten_list(lst))

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


In [ ]:
# 6. Count Occurrences of an Element in a Nested List:
# Write a Python function that counts how many times a specific element appears in a nested list.

def count_occurrences(lst, elem):
    f_list = flatten_list(lst)
    return f_list.count(elem)

count_occurrences([[1,2,3],[1,2,3,2]], 2)

3

In [ ]:
# 7. Flatten a List of Lists of Lists:
# Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

def deep_flatten(lst):
    # convert it to string, strip unnecessary characters
    tmp = str(lst)
    tmp = tmp.strip("[]")
    tmp = tmp.replace("[", "").replace("]", "").replace(" ", "")
    t_arr = tmp.split(",")

    return [int(i) for i in t_arr]

print(deep_flatten([[1, 2], [3, [4, 5]], 6]))

[1, 2, 3, 4, 5, 6]


In [ ]:
# 8. Nested List Average:
# Write a Python function that calculates the average of all elements in a nested list.

def average_nested(lst):
    temp_arr = deep_flatten(lst)
    return sum(temp_arr)/len(temp_arr)

print(average_nested([[1, 2], [3, [4, 5]], 6]))

3.5


# Numpy

In [ ]:
# getting started with the numpy
import numpy as np

zeros_arr = np.zeros((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [ ]:
print(np.array(5)) # scalar value represented as numpy matrix

5


In [ ]:
print(np.array([1,3,4])) # one dimensional matrix

[1 3 4]


In [ ]:
print(np.array([[1,2], [3,4]])) # multi dimensional array

[[1 2]
 [3 4]]


In [ ]:
print(np.array([[1,2], [34]])) # generates error as the shapes of each row does not match

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [ ]:
# Some attributes of numpy array
# 1. ndim - dimension of the array
# 2. dtype - datatype of the array
# 3. shape - shape of the array
# 4. size - total element in the array

print(f"Dimension of array: {one_dim_array.ndim}")
print(f"Datatype of the array: {one_dim_array.dtype}")
print(f"Shape of the array: {one_dim_array.shape}")
print(f"Size of the array: {one_dim_array.size}")

Dimension of array: 1
Datatype of the array: int64
Shape of the array: (3,)
Size of the array: 3


In [ ]:
# itemsize - size in byte of the single element
print(f"Item size: {one_dim_array.itemsize} bytes.")

Item size: 8 bytes.


In [ ]:
# nbytes - total memory consumption of the array in bytes
print(f"Total memory consumption : {one_dim_array.nbytes} bytes.")

Total memory consumption : 24


In [ ]:
# Transpose of the matrix
print(f"Transpose of the matrix \n{n_dim_array} is \n\n{n_dim_array.T}.")

Transpose of the matrix 
[[1 2]
 [3 4]] is 

[[1 3]
 [2 4]].


In [ ]:
# flat - convert the array to one dimension
# .flat Flattening the Array: Returns an iterator over a 1D representation of the array.

for i in n_dim_array.flat:
    print(i, end = ", ")

1, 2, 3, 4, 

In [ ]:
# .real and .imag - Real and Imaginary Parts: Used for complex number arrays.

arr_complex = np.array([1+2j, 3+4j])
print(f"Real : {arr_complex.real}")
print(f"Imaginary : {arr_complex.imag}")

Real : [1. 3.]
Imaginary : [2. 4.]


In [ ]:
# .astype(dtype) Convert Data Type: Converts the array elements to a specified data type.

arr_float = n_dim_array.astype(float)
print(arr_float)
print(arr_float.dtype)

[[1. 2.]
 [3. 4.]]
float64


In [ ]:
# numpy reshape

# changes the shape of the array as long as there are identical count of elements

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
reshaped  = arr.reshape(3,2)
print(reshaped)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# arange

a = np.arange(1, 10)
print(a)

x = range(1, 10)
print(x) # x is an iterator

print(list(x))

# further arange examples:
x = np.arange(1.4)
print(x)

x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[0. 1.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# linspace - generates equally spaced numbers, default = 50
print(np.linspace(1, 10))

# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))

# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


## Creating or Initializing with Ones, Zeros and Empty:

In [ ]:
# np.ones
# np.zeros - create matrix with zero of (n,n)
# np.empty - create empty or uninitialized matrix of (n,n)
# np.eye - identitiy matrix of (n,n)

one_matrix = np.ones((3,4))
print(one_matrix)

zeros_matrix = np.zeros((3,4))
print(zeros_matrix)

empty_matrix = np.empty((3,4))
print(empty_matrix)

eye_mtrix = np.eye(3)
print(eye_mtrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) #
# Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[3.4149929e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


## Stacking methods

In [ ]:
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)

# Stacking examples

hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]

vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]

colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]

print(hstacked, vstacked, colstacked, sep='\n\n')

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 5]
 [2 6]]


In [ ]:
# Concatenation

# Third Argument - axis = 0/1/2

# Example

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

concat_a1_a2 = np.concatenate((arr1,arr2),axis = 0) # vertical stacking
print(concat_a1_a2)

concat_a1_a2 = np.concatenate((arr1,arr2),axis = 1) # horizontal stacking
print(concat_a1_a2)

# concat_a1_a2 = np.concatenate((arr1,arr2),axis = 2) # depth stacking must be three dimensional
# print(concat_a1_a2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# Array Mathematics with NumPy.

In [ ]:
# random array basic operations

arr1 = np.random.rand(3,2)
arr2 = np.random.rand(3,2)

print(np.add(arr1, arr2), np.subtract(arr1, arr2), np.multiply(arr1, arr2), np.divide(arr1,arr2), sep='\n\n')

[[0.49451145 0.78693964]
 [0.68685644 0.32423463]
 [0.89991269 1.90506643]]

[[-0.42356506  0.25107463]
 [-0.43518792  0.09711984]
 [-0.33959443 -0.00143072]]

[[0.01628355 0.13905888]
 [0.07059581 0.02392396]
 [0.17362962 0.90731902]]

[[0.0772772  1.93708163]
 [0.22429462 1.8552489 ]
 [0.45204925 0.99849911]]


In [ ]:
# linear algrebra

import numpy as np
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

product = np.dot(A, B)

# Compute determinant
det = np.linalg.det(A)

# Compute inverse
inverse = np.linalg.inv(A)

# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(f"Matrix Product:\n{product}")
print(f"Determinant: {det}")
print(f"Inverse:\n{inverse}")
print(f"Eigenvalues: {eigvals}, Eigenvectors:\n{eigvecs}")

Matrix Product:
[[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132], Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
import time
# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)

# Using a loop
start_time = time.time()
result_loop = np.zeros(size)

for i in range(size):
    result_loop[i] = a[i] + b[i]
end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")

# Using NumPy’s vectorized operations
start_time = time.time()

result_vectorized = a + b # Element-wise addition
end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")

# Performance improvement factor
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 0.45075 seconds
Vectorized Execution Time: 0.00905 seconds
Vectorization is approximately 49.79 times faster!


# TODO - NUMPY

In [ ]:
# Problem - 1: Array Creation:

# Complete the following Tasks:
# 1. Initialize an empty array with size 2X2.
e_arr = np.empty((2,2))

# 2. Initialize an all one array with size 4X2.
o_arr = np.ones((4,2))

# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
full_arr = np.full((4,2), 10, dtype='float32')

# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
zeros_like_arr = np.zeros_like(np.array([[1,2],[3,4]]))

# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
ones_arr = np.ones_like(np.array([1,2,3,4]))

# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]
arr = np.array(new_list)

print(e_arr, o_arr, full_arr, zeros_like_arr, ones_arr, arr, sep='\n\n')


[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]

[[0 0]
 [0 0]]

[1 1 1 1]

[1 2 3 4]


In [ ]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
# Complete the following tasks:

# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
ten_to_forty_nine = np.arange(10,49)
print(ten_to_forty_nine)

# 2. Create a 3X3 matrix with values ranging from 0 to 8.
zero_to_eight = np.arange(0,8)
print(zero_to_eight)

# {Hint:look for np.reshape()}

# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix = np.eye(3)
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
rand_arr = np.random.rand(30).mean()
print("mean: " , rand_arr)

# {Hint:check for np.random.random() and array.mean() function}

# 5. Create a 10X10 array with random values and find the minimum and maximum values.
ten_by_ten = np.random.rand(10,10)
print("max: ", ten_by_ten.max())
print("min: ", ten_by_ten.min())

# 6. Create a zero array of size 10 and replace 5th element with 1.
size_ten = np.zeros((10,1))
size_ten[5] = 1
print(size_ten)

# 7. Reverse an array arr = [1,2,0,0,4,0].
reverse_arr = np.array([1,2,0,0,4,0][::-1])
print(reverse_arr)

# 8. Create a 2d array with 1 on border and 0 inside.
array = np.ones((3, 4))
array[1:-1, 1:-1] = 0
print(array)

# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
eight_by_eight = np.ones((8,8))
eight_by_eight[1::2, ::2] = 0
eight_by_eight[::2, 1::2] = 0
print(eight_by_eight)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[0 1 2 3 4 5 6 7]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
mean:  0.38799254062259514
max:  0.9940546714907287
min:  0.0014714422298330865
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0 4 0 0 2 1]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
# Problem - 3: Array Operations:
# For the following arrays:

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

# Complete all the task using numpy:

# 1. Add the two array.
print("ADD: ", x+y)

# 2. Subtract the two array.
print("SUBTRACT: ",x-y)

# 3. Multiply the array with any integers of your choice.
print("SCALAR MULTIPLICATION: ", 3 * x)

# 4. Find the square of each element of the array.
print("SQUARE OF X: ",np.square(x))

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print("DOT MULTIPLICATION OF V AND W:",np.dot(v,w))
print("DOT MULTIPLICATION OF X AND V:",np.dot(x,v))
print("DOT MULTIPLICATION OF X AND Y:",np.dot(x,y))

# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
print("CONCATENATE X AND Y ALONG ROW: ",np.concatenate((x,y),axis=1))
print("CONCATENATE V AND W: ", np.concatenate((v,w),axis=0))

# {Hint:try np.concatenate() or np.vstack() functions.

# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
print("CONCATENATE X AND V: ", np.concatenate((x,v),axis=0)) # ERROR as the dimension of x and v do not match

ADD:  [[ 6  8]
 [10 13]]
SUBTRACT:  [[-4 -4]
 [-4 -3]]
SCALAR MULTIPLICATION:  [[ 3  6]
 [ 9 15]]
SQUARE OF X:  [[ 1  4]
 [ 9 25]]
DOT MULTIPLICATION OF V AND W: 219
DOT MULTIPLICATION OF X AND V: [29 77]
DOT MULTIPLICATION OF X AND Y: [[19 22]
 [50 58]]
CONCATENATE X AND Y ALONG ROW:  [[1 2 5 6]
 [3 5 7 8]]
CONCATENATE V AND W:  [ 9 10 11 12]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# Problem - 4: Matrix Operations:
# • For the following arrays:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

# Prove following with Numpy:
# 1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv))

# 2. Prove AB = ̸= BA.
AB = np.dot(A,B)
BA = np.dot(B,A)

print((AB == BA).all())

# 3. Prove (AB)T = B(T).A(T)
print((AB.T == np.dot(B.T, A.T)).all())

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
False
True


In [ ]:
# • Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
b = np.array([-1,-3,9])
print(np.linalg.solve(A, b))

# {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

# • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
# tion of Numpy}

[ 2.  1. -2.]
